### ISSUE TITLE
[bug]: interaction with nvim-dap-ui causes windows size problems

### ISSUE THREAD

**Issue by franksl** [shortcuts/no-neck-pain.nvim#470]
### Description

Hi,
I have both no-neck-pain and nvim-dap-ui on my setup. 
When activating/deactivating nvim-dap-ui multiple times the dap-ui main window gets resized to the right by a portion each time. When deactivating dap the no-neck-pain window appears correctly.
For example the first activation of dap-ui is like this on a php file:

![Image](https://github.com/user-attachments/assets/0664873b-91b6-4b5f-8db1-205f8b8c19e6)

after a couple of activation/deactivations it becaomes like this:

![Image](https://github.com/user-attachments/assets/16533e0a-91da-408f-984a-c12c2920a207)

If I remove no-neck-pain from my setup this does not happen, so I onestly don't know which plugin causes the problem.
Many thanks

### Neovim version

0.10.x

### Steps to reproduce

1. open nvim with no-neck-pain
2. activate / deactivate debugging with nvim-dap-ui
3. the main dap window gets resized each time

### Relevant log output

```shell

```

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by shortcuts** [comment]
hey! thanks for using the plugin and reporting the issue :)

this should be fixed by https://github.com/shortcuts/no-neck-pain.nvim/pull/469, i'll try to finish it this evening

**Comment by shortcuts** [comment]
Hey @franksl, could you please share your no-neck-pain config and nvim-dap-ui as well if possible? I'm not able to reproduce

**Comment by shortcuts** [comment]
Hey so https://github.com/shortcuts/no-neck-pain.nvim/pull/474/ should not properly fix the issue for dap, however I have an incoming PR that should cover it

**Comment by franksl** [comment]
Hi,
Here's my pretty much standard config for no-neck-pain:
```
return {
    "shortcuts/no-neck-pain.nvim",
    version = "*",
    config = function (_, opts)
        require("no-neck-pain").setup({
            width = 140,
            autocmds = {
                enableOnVimEnter = true,
                skipEnteringNoNeckPainBuffer = true
            },
            buffers = {
                right = {
                    enabled = false,
                },
                wo = {
                    fillchars = "eob: ",
                }
            },
        })
    end
}

```

And here is my dap plugins config:
```
return {
    "mfussenegger/nvim-dap",
    dependencies = {
        "leoluz/nvim-dap-go",
        "rcarriga/nvim-dap-ui",
        "nvim-neotest/nvim-nio",
        "williamboman/mason.nvim",
        "theHamsta/nvim-dap-virtual-text",
        "rinx/nvim-dap-rego"
    },
    config = function (_, opts)
        local dap = require("dap")
        local dapui = require("dapui")
        dapui.setup()

        require("nvim-dap-virtual-text").setup({
        })

        -- PHP
        dap.adapters.php = {
            type = "executable",
            command = "node",
            args = { os.getenv("HOME") .. "/bin/vscode-php-debug/out/phpDebug.js" }
        }
        dap.configurations.php = {
            {
                type = "php",
                request = "launch",
                name = "Listen for Xdebug",
                port = 9003
            }
        }

        vim.keymap.set('n', '<F5>', dap.continue)
        vim.keymap.set('n', '<F10>', dap.step_over)
        vim.keymap.set('n', '<F11>', dap.step_into)
        vim.keymap.set('n', '<F12>', dap.step_out)
        vim.keymap.set('n', '<Leader>b', dap.toggle_breakpoint)

        dap.listeners.before.attach.dapui_config = function()
            dapui.open()
        end
        dap.listeners.before.launch.dapui_config = function()
            dapui.open()
        end
        dap.listeners.before.event_terminated.dapui_config = function()
            dapui.close()
        end
        dap.listeners.before.event_exited.dapui_config = function()
            dapui.close()
        end
        dap.listeners.before.disconnect.dapui_config = function()
            dapui.close()
        end
    end
}

```

I can confirm that v2.4.5 does not solve my problem,
Thanks

**Comment by shortcuts** [comment]
Hello! Would you mind trying this branch https://github.com/shortcuts/no-neck-pain.nvim/tree/feat/integrations and letting me know if you can still encounter this issue? Thanks a lot!

**Comment by franksl** [comment]
Hi,
I tried the branch but unfortunately the problem persists. I'm now using nvim 0.12 with vim.pack for setup, I made sure it was using the correct branch.
Thanks

**Comment by franksl** [comment]
I tested with 3.0.0, while setting:
```   
vim.pack.add({
    {
        src = "https://github.com/shortcuts/no-neck-pain.nvim",
    },
})

require("no-neck-pain").setup({
    width = 140,
    autocmds = {
	    enableOnVimEnter = true,
	    skipEnteringNoNeckPainBuffer = true
    },
    buffers = {
        right = {
            enabled = false,
        },
        wo = {
            fillchars = "eob: ",
        }
    },
    integrations = {
        dap = {
            position = "none"
        }
    }
})

```
I usually only use a left buffer to center my main content.
When activating dap-ui, the dap windows open and close without changes between sessions, but I also get the no-neck-pain buffer open, while I was expecting it to disappear and leave all the screen for the dap buffers. What should I do to make it disappear when dap is open? Usually when I have a vertical split, the no-neck-pain buffer disappears.
Also if I set dap position to "right" I still get the old problem that the main buffer shrinks to the right.
Thanks

**Comment by shortcuts** [comment]
hello! I pushed a fix on main which should hopefully improve the support of dap, it's kind of complicated to get it right due to the number of windows created from the plugin

and also thanks a lot for testing v3 already :D

**Comment by franksl** [comment]
Hi, unfortunately now the situation is worse than before..
- the first time I activate dap:ui I getthe screen split in two identical windows vertically (which could be acceptable but instead the right section should be larger than the left one)
- closing dap-ui and reactivating it causes the original problem, the rightmost window becomes narrower each time I open the dap-ui

I don't have any particular knowledge of vim internals, so this is just a question: isn't it possible to just disable no-neck-pain when any dap window is created, so that dap-ui takes control of the ui? (which is what I'd expect)

Thanks
